// Builds the prototype so it also works opened straight from disk (file://):
//   1. sample-assets.js  ← sample/fleet-proposal.pptx and sample/images/*.png as base64
//   2. index.html        ← index.src.html with the kit's icon sprite inlined
//   3. app.bundle.js     ← app.js + imports + @aiden0z/pptx-renderer + JSZip, one IIFE
import fs from 'node:fs';
import path from 'node:path';
import * as esbuild from 'esbuild';

const root = path.resolve(path.dirname(new URL(import.meta.url).pathname), '..');
const b64 = (f) => fs.readFileSync(f).toString('base64');

const images = {};
for (const f of fs.readdirSync(path.join(root, 'sample/images')).filter((f) => f.endsWith('.png')).sort()) images[f.replace(/\.png$/, '')] = b64(path.join(root, 'sample/images', f));
fs.writeFileSync(path.join(root, 'sample-assets.js'),
  '// Generated by vendor-src/build.mjs from sample/. Base64 so the page works from file:// (no fetch).\n' +
  `export const ASSETS = ${JSON.stringify({ deck: b64(path.join(root, 'sample/fleet-proposal.pptx')), images }, null, 0)};\n`);

const sprite = fs.readFileSync(path.join(root, 'vendor/sdocs-kit/icons.svg'), 'utf8')
  .replace(/^<svg[^>]*>/, '<svg class="sd-icon-sprite" hidden aria-hidden="true" xmlns="http://www.w3.org/2000/svg" style="display:none">');
fs.writeFileSync(path.join(root, 'index.html'), fs.readFileSync(path.join(root, 'index.src.html'), 'utf8').replace('<!--SPRITE-->', sprite));

const res = await esbuild.build({
  entryPoints: [path.join(root, 'app.js')], bundle: true, format: 'iife', minify: true, target: 'es2020',
  outfile: path.join(root, 'app.bundle.js'), define: { 'process.env.NODE_ENV': '"production"' },
  nodePaths: [path.join(root, 'vendor-src/node_modules')], metafile: true, logLevel: 'warning', legalComments: 'eof'
});
const kb = (n) => (n / 1024).toFixed(0) + ' KB';
console.log('app.bundle.js', kb(fs.statSync(path.join(root, 'app.bundle.js')).size));
const top = Object.entries(res.metafile.outputs[Object.keys(res.metafile.outputs)[0]].inputs)
  .map(([k, v]) => [k.replace(/.*node_modules\//, '').split('/').slice(0, k.includes('@') ? 2 : 1).join('/'), v.bytesInOutput])
  .reduce((m, [k, v]) => m.set(k, (m.get(k) || 0) + v), new Map());
console.log([...top].sort((a, b) => b[1] - a[1]).slice(0, 8).map(([k, v]) => `  ${k} ${kb(v)}`).join('\n'));
